repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=80000"]
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types: [sql]
      - id: trailing-whitespace
        exclude_types: [c, sql]
  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier
        exclude: CHANGELOG.md
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black src/ tests/
        language: system
        stages: [commit]
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort src tests build.py noxfile.py
        language: system
        stages: [commit]
        types: [python]
